environment:
  global:
    PROJECT_NAME: build-version-win64
  matrix:
    - TARGET: x86_64-pc-windows-gnu
      RUST_VERSION: 1.24.0

install:
  - SET RUST_URL=https://static.rust-lang.org/dist/rust-%RUST_VERSION%-%TARGET%.exe
  - SET PATH=C:\Rust\bin;C:\msys64\mingw64\bin;%PATH%;C:\msys64\usr\bin
  - SET PKG_CONFIG_PATH=C:\msys64\mingw64\lib\pkgconfig
  - ps: Start-FileDownload $env:RUST_URL -FileName rust-dist.exe
  - rust-dist.exe /VERYSILENT /NORESTART /COMPONENTS="Rustc,Gcc,Cargo,Std" /DIR="C:\Rust"
  - rustc -V
  - cargo -V

build_script:
  - cargo test
